Added job in CI to verify license generation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -170,8 +170,8 @@ jobs:
       - name: Scorecard
         run: make bundle-scorecard
 
-  check-diff:
-    name: Check diff
+  gen:
+    name: Generate artifacts
     runs-on: ubuntu-latest
     needs: detect-noop
     if: ${{ needs.detect-noop.outputs.noop != 'true' }}
@@ -186,3 +186,22 @@ jobs:
         uses: mmontes11/diff-porcelain@v0.0.1
         with:
           message: Generated artifacts are not up to date. Run 'make generate' and commit the changes.
+
+  licenses:
+    name: Generate licenses
+    runs-on: ubuntu-latest
+    needs: detect-noop
+    if: ${{ needs.detect-noop.outputs.noop != 'true' }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Generate
+        run: make licenses
+
+      - name: Check licenses
+        run: |
+          if [ ! -d "licenses" ] || [ ! -n "$(ls -A licenses)" ]; then
+            echo "Error: No licenses generated"
+            exit 1
+          fi
